## 

## 

In [28]:
import numpy as np

print("MATRIX 1\n") 
r1= int(input("Enter the number of rows:")) 
c1= int(input("Enter the number of columns:"))

print("Enter the elements in a single line (space separated): ")

ent1=list(map(int, input().split()))

mat1=np.array(ent1).reshape(r1, c1) 
print("\n Matrix 1 : \n", mat1)

print("\nMARTIX 2 \n") 
r2= int(input("Enter the number of rows:")) 
c2= int(input("Enter the number of columns:"))

print("Enter the elements in a single line (space separated): ")

ent2=list(map(int, input().split()))

mat2=np.array(ent2).reshape(r2, c2) 
print("\n Matrix 2 : \n", mat2)

#1 : DOT PRODUCT 
b=np.dot(mat1,mat2) 
print("\n Dot product : \n",b)

#2 : TRANSPOSE 
trans=np.transpose(mat1) 
print("\n Transpose of Matrix : \n",trans)

#3 : TRACE 
trace=np.trace(mat1) 
print("\n Trace of Matrix : \n",trace)

#4 : RANK 
rank=np.linalg.matrix_rank(mat1) 
print("\n Rank of Matrix : \n",rank)

#5 : DETERMINANT 
det=np.linalg.det(mat1) 
print("\n Determinant of Matrix : \n",det)

#6 : INVERSE 
inv=np.linalg.inv(mat1) 
print("\n Inverse of Matrix : \n",inv)

#7 : EIGEN VALUES & EIGEN VECTORS 
eig=np.linalg.eig(mat1) 
print("\n Eigen values and Eigen vectors : \n",eig)


MATRIX 1



Enter the number of rows: 2
Enter the number of columns: 2


Enter the elements in a single line (space separated): 


 1 2 3 4



 Matrix 1 : 
 [[1 2]
 [3 4]]

MARTIX 2 



Enter the number of rows: 2
Enter the number of columns: 2


Enter the elements in a single line (space separated): 


 4 3 2 1



 Matrix 2 : 
 [[4 3]
 [2 1]]

 Dot product : 
 [[ 8  5]
 [20 13]]

 Transpose of Matrix : 
 [[1 3]
 [2 4]]

 Trace of Matrix : 
 5

 Rank of Matrix : 
 2

 Determinant of Matrix : 
 -2.0000000000000004

 Inverse of Matrix : 
 [[-2.   1. ]
 [ 1.5 -0.5]]

 Eigen values and Eigen vectors : 
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
