In [25]:
#exercise 1: element wise comparison
import numpy as np
a=np.array([7,2,3])
b=np.array([4,5,3])
print("Greater")
print(np.greater(a,b))
print(np.greater_equal(a,b))
print("Less")
print(np.less_equal(a,b))
print(np.less(a,b))


Greater
[ True False False]
[ True False  True]
Less
[False  True  True]
[False  True False]
[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
c=np.arange(1,11)
print(c)
c.reshape(5,2)

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
#exercise 2: all even numbers within a range
print(np.arange(30,70,2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [24]:
#exercise 3: 3x3 identity matrix
a=np.identity(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [13]:
#exercise 4: change sign of numbers in a range 
s=np.arange(21)
print("Original Array : \n",s)
print("After changing the sign of the numbers in the range from 9 to 15:")
s[(s >= 9) & (s <= 15)] *= -1
print(s)

Original Array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [3]:
#exercise 5: zero matrix with diagonal 1,2,3,4,5
print(np.diag([1,2,3,4,5]))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [12]:
#exercise 6: sum of all elements, each column, each row of an array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Sum of all elements : ",np.sum(a))
print("Sum of each column : ",np.sum(a,axis=0))
print("Sum of each column : ",np.sum(a,axis=1))

Sum of all elements :  45
Sum of each column :  [12 15 18]
Sum of each column :  [ 6 15 24]


In [14]:
#exercise 7: save a given array to a text file and load it
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.savetxt('new.txt',a)
t=np.loadtxt('new.txt')
print(t)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [27]:
#exercise 8: save a given array to a text file and load it
a=np.array([7,2,3])
b=np.array([4,5,3])
#print("Equal (True/False) : ",np.array_equal(a,b))
res=np.array_equal(a,b)
print("Equal" if res==True else "Not Equal")

Not Equal


In [15]:
#exercise 9: take a 4x4 array, create new array from the given array with 1st & last row swapped
# arr=np.array([[0,0,0,0],[2,2,2,2],[3,3,3,3],[1,1,1,1]])
# arr=np.random.rand(3,4)
arr=np.random.randint(1,30,(4,4))
print("Original Array : \n",arr)
arr[[0,3]]=arr[[3,0]]
print("Swapped Array :\n",arr)

Original Array : 
 [[12 14 22 21]
 [19 25 27  3]
 [23 15  9 17]
 [22  2 10 15]]
Swapped Array :
 [[22  2 10 15]
 [19 25 27  3]
 [23 15  9 17]
 [12 14 22 21]]


In [38]:
#exercise 10: multiply 2 given array of same size element-by-element
import numpy as np
a=np.array([[1,1,1],[1,2,3]])
print("Array 1 : ",a)
b=np.array([[4,3,2],[1,1,1]])
print("Array 2 : ",b)
print("Array after muliplying : ")
print(np.multiply(a,b))


Array 1 :  [[1 1 1]
 [1 2 3]]
Array 2 :  [[4 3 2]
 [1 1 1]]
Array after muliplying : 
[[4 3 2]
 [1 2 3]]
