In [2]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([6,1,7,8])

In [3]:
np.greater(a,b)

array([False,  True, False, False])

In [4]:
np.greater_equal(a,b)

array([False,  True, False, False])

In [5]:
np.less(a,b)

array([ True, False,  True,  True])

In [6]:
np.less_equal(a,b)

array([ True, False,  True,  True])

In [8]:
e=np.arange(30,70,2)
print(f'Array of even number elements from 30 to 70 : {e}')

Array of even number elements from 30 to 70 : [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


In [9]:
i=np.identity(3,dtype=int)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [15]:
v=np.arange(0,20)
v[(v>=9)&(v<=15)] *=-1
print(v)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


In [16]:
a=np.diag(np.arange(1,6))
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [18]:
a=np.array([[1,2,3],
          [1,1,1],
          [0,0,0]])
print(np.sum(a))

9


In [19]:
print(np.sum(a,axis=0))

[2 3 4]


In [20]:
print(np.sum(a,axis=1))

[6 3 0]


In [21]:
np.savetxt('array.txt',a)

In [23]:
print(np.loadtxt('array.txt').astype(np.int64))

[[1 2 3]
 [1 1 1]
 [0 0 0]]


In [25]:
a=np.array([[1,2,3],
          [1,1,1],
          [0,0,0]])
b=np.array([[1,2,3],
          [1,1,21],
          [0,0,0]])
print(np.array_equal(a,b))

False


In [47]:
r=np.random.rand(4,4)
r=np.round(r,1)
# r=np.random.randint(1,100,(4,4))
# print(a)
print(f'Before Swap :\n {r}')
r[0,3]=r[3,0]
print(f'\nAfter Swap :\n {r}')

Before Swap :
 [[0.  0.5 0.7 0.9]
 [0.3 0.6 0.6 0.7]
 [0.9 0.5 0.5 0.2]
 [0.1 0.6 0.7 0.9]]

After Swap :
 [[0.  0.5 0.7 0.1]
 [0.3 0.6 0.6 0.7]
 [0.9 0.5 0.5 0.2]
 [0.1 0.6 0.7 0.9]]


In [50]:
a=np.array([[1,2,3],
           [2,1,1]])
b=np.array([[1,2,3],
           [1,1,1]])
print(f'Product : \n{a*b}')

Product : 
[[1 4 9]
 [2 1 1]]
